FROM node:14 as builder

WORKDIR /usr/app

COPY package.json /usr/app
COPY package-lock.json /usr/app

RUN npm install

COPY . .

RUN npm run build
#above container is temporarily container

FROM nginx
# with this FROM we say that previous block is terminated
COPY  --from=builder /usr/app/build /usr/share/nginx/html



